"""Shared pytest fixtures.

The corpus is generated by ``scripts/make_fixtures.py``.  Tests that need a
fixture which the local Python cannot produce (no openpyxl, no PyMuPDF, ...) are
skipped rather than failed, so the suite stays honest on a bare install -- the
same philosophy as the converters themselves.
"""

from __future__ import annotations

import itertools
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "tests" / "fixtures"
#: Scratch space inside the workspace.  pytest's default temp root lives under
#: %LOCALAPPDATA%, which is not always writable (sandboxes, locked-down
#: machines), and a test suite that cannot create a temp directory is useless.
TMP_ROOT = ROOT / ".tmp" / "tests"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def pytest_configure(config: pytest.Config) -> None:
    """Generate the corpus on first run so a fresh checkout can just pytest."""
    shutil.rmtree(TMP_ROOT, ignore_errors=True)
    if FIXTURES.exists() and any(FIXTURES.iterdir()):
        return
    script = ROOT / "scripts" / "make_fixtures.py"
    subprocess.run([sys.executable, str(script)], check=False, cwd=str(ROOT))


_counter = itertools.count()


@pytest.fixture()
def tmp_path(request: pytest.FixtureRequest) -> Path:
    """Workspace-local replacement for pytest's ``tmp_path``.

    Same contract: a fresh, writable, per-test directory -- just not under the
    system temp root.  Per-test directories are kept (not wiped) so a failing
    test leaves its inputs behind for inspection; ``pytest_configure`` clears
    the whole tree at the start of each session.
    """
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", request.node.name)[:80]
    path = TMP_ROOT / f"{next(_counter):04d}-{safe}"
    path.mkdir(parents=True, exist_ok=True)
    return path


@pytest.fixture(scope="session")
def fixtures() -> Path:
    if not FIXTURES.exists():
        pytest.skip("test corpus could not be generated")
    return FIXTURES


@pytest.fixture()
def fixture(fixtures: Path):
    """``fixture("report.pdf")`` -> Path, skipping when it was not generated."""

    def _get(name: str) -> Path:
        path = fixtures / name
        if not path.exists():
            pytest.skip(f"fixture {name} not available in this environment")
        return path

    return _get


@pytest.fixture()
def outdir(tmp_path: Path) -> Path:
    return tmp_path / "out"


@pytest.fixture()
def convert_fixture(fixture, outdir):
    """Convert a fixture and return ``(result, markdown_text)``."""
    from tomd import ConvertOptions, convert, render

    def _convert(name: str, **option_kwargs):
        options = ConvertOptions(
            output_dir=outdir, front_matter=False, report=False, **option_kwargs
        )
        result = convert(fixture(name), options, write=True)
        return result, render(result, options)

    return _convert
